[build]
  base = "."
  command = "npm install && npm run build:client"
  publish = "dist/public"

[[redirects]]
  from = "/api/*"
  to = "https://studio-maestro-api.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
